---
title: "Homework_12"
author: "Andrew McCracken"
date: "4/13/2022"
output: html_document
---
[Home Page](index.html)

### Importing and formatting data from phyloseq objects
```{r}
# Taxa Bar plots form Plyloseq Data
# Andrew McCracken
# 4/13/22

setwd("C:/Users/andre/Desktop/Pespeni Lab/SSWD Pycnopodia 16s Networks Manuscript/Taxa-bar-plots")

# Load Libraries (idk if you need them all but here we go) 
library(microbiome)
library(phyloseq)
library(qiime2R)
library(knitr)
library(kableExtra)
#install.packages("remotes")
#remotes::install_github("gmteunisse/Fantaxtic")
library(remotes)
library(fantaxtic)
library(reshape2)
library(tidyverse)
library(sjmisc)


# import phyloseq files
physeq_all<-qza_to_phyloseq(
  features="table.qza",
  tree="rooted-tree.qza",
  taxonomy="taxonomy.qza",
  metadata = "pyc_manifest")

#Filter to Family Level
filter_fam <- tax_glom(physeq_all, "Family")

#normalize per individual sample. 
norm_abund_fam <- transform_sample_counts(filter_fam, function(x) x / sum(x))

#Filter top taxa
#https://rdrr.io/github/gmteunisse/Fantaxtic/man/get_top_taxa.html
top_tax_merge <- get_top_taxa(norm_abund_fam, 15, relative = TRUE, discard_other = FALSE, other_label = "Other")


# Phyloseq Plot
#plot_bar(top_tax_merge, "animalID", "Abundance", fill="Family")
```

#### Converting Phyloseq object to Data.Frame for ggplot

```{r}
########################################################
# convert to data table
setwd("C:/Users/andre/Desktop/Pespeni Lab/SSWD Pycnopodia 16s Networks Manuscript/Taxa-bar-plots")
source('phyloseq_to_df.R')
phylo_table_fam_all <- phyloseq_to_df(norm_abund_fam)
phylo_table_fam_15 <- phyloseq_to_df(top_tax_merge)


# Randomly sample 5 from HH, 5 SH, 5 SS
# Col 9-55 -> HH
# Col 56-75 -> SH
# Col 76-93 -> SS

subset_fam_15 <- cbind(phylo_table_fam_15[,6], 
                       sample(x = phylo_table_fam_15[,9:55], size=5),
                       sample(x = phylo_table_fam_15[,56:75], size=5),
                       sample(x = phylo_table_fam_15[,76:93], size=5))

subset_fam_15_rotate <- rotate_df(subset_fam_15, rn = "sample", cn = TRUE)


fam_15_long <- pivot_longer(subset_fam_15, 
                            col=2:16,  
                            names_to = 'Sample', 
                            values_to = 'Abundance')

names(fam_15_long)[1] <- 'taxa'

#Relative Abundance 
group_by(fam_15_long, taxa)
ggplot(data=fam_15_long) + geom_bar(aes(x=Sample, y=Abundance, fill=taxa), stat="identity")
```

