---
title: "Homework_03"
author: "Andrew McCracken"
date: "2/2/2022"
output: html_document
---

[Home Page](index.html)

## Solution 1
```
Find: \t+
Replace: ,
```
Explanation: The original file was a tab-delimated file and we wanted items to be separated by commas instead. I searched for every palace there was a tab and replaced it with a comma. 

## Solution 2
```
Find: (\w+,) (\w+,) (.*)
Replace: \2 \1 \(\3\)
```
Explanation: Captured the first name with `(\w+,)` and another `(\w+,)` to capture the second (one or more consecutive word characters for each) then used (.*) to capture everything else that came after. Then reordered these elements placing the second capture first, and the first capture second, then adding parenthesis around the third element.  

## Solution 3
```
Find: mp3(\s)
Replace: mp3\n
```

Explanation: First I captured each song by finding the mp3 followed by a space. and replaced these with the mp3 followed by a `\n` to put the next element on the line below it. 

## Solution 4
```
Find: (\d{4})(.*)(\.mp3)
Replace: \2_\1\3
```
Explanation: I captured the first four didgets with `(\d{4})`, then everything after that until .mp3. I reordered these captures by placing the consecutive word characters captured by `.*` and added an underscore. Moved the first four didgets after that underscore character and then the rest o the .mp3. 

## Solution 5
```
Find: (\w)\w+,(\w+),\d+.*,(\d+)
Replace: \1_\2,\3
```
Explanation: I captured the first letter of the first word (genus name), the second word (species name), and the last numeric variable (\d+) for each line. then i only kept these comoonents and added a comma after the second element and before the third capture (the last numeric variable)

## Solution 6
```
Find: (\w)\w+,(\w{4})\w+,\d+.*,(\d+)
Replace: \1_\2,\3
```
Explanation: I did the same as question 5 but instead of grabbing the entre second word, i grabbed the first our characters of that word with `(\w{4})`. I kept the first element followed by an underscore, the seocond followed by a comma, and finally followed by the last number.

## Solution 7
```
Find: (\w{3})\w+,(\w{3})\w+,(\d+.*),(\d+)
Replace: \1\2, \4, \3
```
Explanation: Here I captured the first 3 characters of the genus name, the first 3 letters of the species name with `\w{3}`, and then captured the last two numbers seperately with `(\d+.*)`and `(\d+)`. for the replace function, i concatonated the first 3 letters of species and genus together, adda comma and space, then placed the second number in the original list, then the first number (putting the numeric values in the desired order)

